REGISTER_SUCCESS = 'REGISTER_SUCCESS';
REGISTER_FAIL = 'REGISTER_FAIL';
USER_LOAD = 'USER_LOAD';
AUTH_ERROR = 'AUTH_ERROR';
LOGIN_SUCCESS = 'LOGIN_SUCCESS';
LOGIN_FAIL = 'LOGIN_FAIL';
LOGOUT = 'LOGOUT';
CLEAR_ERROR = 'CLEAR_ERRORS';
